export const WORK_HOURS_PER_DAY = 8;
export const WORK_DAYS_PER_WEEK = 5;
export const WEEKS_PER_YEAR = 52;
export const MONTHS_PER_YEAR = 12;

export const WORK_HOURS_PER_WEEK = WORK_HOURS_PER_DAY * WORK_DAYS_PER_WEEK; // 40
export const WORK_HOURS_PER_FORTNIGHT = WORK_HOURS_PER_WEEK * 2; // 80
export const WORK_HOURS_PER_YEAR = WORK_HOURS_PER_WEEK * WEEKS_PER_YEAR; // 2080
export const WORK_HOURS_PER_MONTH = WORK_HOURS_PER_YEAR / MONTHS_PER_YEAR; // 173.33333333333334
export const WORK_DAYS_PER_YEAR = WORK_DAYS_PER_WEEK * WEEKS_PER_YEAR; // 260
